### PR TITLE
Add code to add checkpoints

### PR DESCRIPTION
**Pull request by rubensayshi**
Goes hand-in-hand with counterparty-lib PR: https://github.com/CounterpartyXCP/counterparty-lib/pull/866

### CODE REVIEW

**Comment by robby-dermody** [comment]
what about adding command line options to turn on/off checkpoint and stored hash verification via cmd line and config file settings? (server.init takes the args with the `counterparty-lib` PR, but you are not passing those in in `-cli`)

**Comment by rubensayshi** [comment]
oh must have lost those between moving branches

**Comment by rubensayshi** [comment]
added those and renamed to stored hash

**Comment by robby-dermody** [comment]
great, please reopen against `develop-evm` and I will merge

**Comment by chiguireitor** [comment]
Related -lib PR was closed without merging, so closing this one as it seems to be related to evm development

**Pull request closed without merging**
